# Generated by Django 3.0.5 on 2021-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tokenBlackList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255)),
                ('block_until_date', models.DateTimeField(blank=True, null=True)),
                ('block_token', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
    ]
