# Generated by Django 3.0.5 on 2021-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenblacklist',
            name='block_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
